"""empty message

Revision ID: 19e3909dc5b4
Revises: 48c79871bd4b
Create Date: 2012-04-07 13:52:41.719422

"""

# revision identifiers, used by Alembic.
revision = '19e3909dc5b4'
down_revision = '48c79871bd4b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.Text(), nullable=True),
    sa.Column('role', sa.Unicode(length=25), nullable=True),
    sa.Column('action', sa.Unicode(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('acls')
    ### end Alembic commands ###
