"""empty message

Revision ID: 2a063644e55f
Revises: 19e3909dc5b4
Create Date: 2012-04-08 00:03:47.584909

"""

# revision identifiers, used by Alembic.
revision = '2a063644e55f'
down_revision = '19e3909dc5b4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acls', sa.Column('permissions', sa.TEXT(), nullable=True))
    op.drop_column('acls', u'permission')
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acls', sa.Column(u'permission', sa.TEXT(), nullable=True))
    op.drop_column('acls', 'permissions')
    ### end Alembic commands ###
