"""Inital db

Revision ID: 670424a6e5
Revises: None
Create Date: 2012-03-27 23:42:43.877470

"""

# revision identifiers, used by Alembic.
revision = '670424a6e5'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('models')
    ### end Alembic commands ###
