"""empty message

Revision ID: 9429e342ff7
Revises: 2a063644e55f
Create Date: 2012-04-08 18:45:01.548275

"""

# revision identifiers, used by Alembic.
revision = '9429e342ff7'
down_revision = '2a063644e55f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_group',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint()
    )
    op.drop_table(u'acls')
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'acls',
    sa.Column(u'id', sa.INTEGER(), server_default="nextval('acls_id_seq'::regclass)", nullable=False),
    sa.Column(u'role', sa.VARCHAR(length=25), nullable=True),
    sa.Column(u'action', sa.VARCHAR(length=5), nullable=True),
    sa.Column(u'permissions', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint(u'id', name=u'acls_pkey')
    )
    op.drop_table('user_group')
    op.drop_table('groups')
    ### end Alembic commands ###
